### ISSUE TITLE
[docker/IntelliJ] - DB 생성 및 연동 

### ISSUE THREAD

**Issue by berryberrybin** [berryberrybin/spring-batch#4]
1. docker MYSQL DB 생성

- 명령어
   - `docker run -d -p 3307:3306 -e MYSQL_ROOT_PASSWORD=pass -e MYSQL_DATABASE=batch --name mysql3307 mysql:5.7`
      - `3307 : 3306` [ 지정 port ]  :  [ 기본 port ] 
      - `-e MYSQL_DATABASE=batch` 컨테이너의 이미지를 시작 하면서 지정한 데이터베이스를 생성
 
![image](https://user-images.githubusercontent.com/67494127/182305102-7b88721c-e288-40c9-9f99-f02d79506533.png)

![image](https://user-images.githubusercontent.com/67494127/182305493-d683a23e-ded6-481f-8273-ba2af475fab9.png)

**Comment by berryberrybin** [comment]
2. IntelliJ database 연동
![IMG_C186475833DF-1](https://user-images.githubusercontent.com/67494127/182306920-c74352af-5fc1-4867-a731-44b19cb9a439.jpeg)

**Comment by berryberrybin** [comment]
3. application.yml 파일

``` yml
spring:
  profiles:
    active: mysql  #어떤 DB 사용할지 설정 
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    properties:
      hibernate.format_sql: true
  batch:
    jdbc:
      initialize-schema: always

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:~/dbname;MODE=MySQL;DATABASE_TO_LOWER=TRUE
      username: sa
      password:
      driver-class-name: org.h2.Driver

---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3307/batch?useUnicode=true&characterEncoding=utf8
      username: root
      password: pass
      driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    job:
      names: ${job.name:NONE}
#      enabled: false
    jdbc:
      initialize-schema: always
```
